### ISSUE TITLE
Simplify uncover

### ISSUE THREAD

**Issue by paf31** [nicodelpiano/stlcnat-exhaustivity-checker#2]
I think we can write it like this:

``` haskell
instance Match Binder where
  missed _ NullBinder = []

  missed NullBinder b = go b
    where 
    go Zero = [Succ NullBinder]
    go (Succ n) = Zero : map Succ (go n)

  missed Zero Zero = []
  missed (Succ n) (Succ m) = map Succ (missed n m)

  missed b _ = [b]
```

That is, we have four groups of cases:
- `NullBinder` matches everything
- If we start with `NullBinder`, we take the complement of the pattern
- If the patterns match exactly, we return `[]` (this bit looks like unification)
- Everything else fails to match - return the argument.

This should hopefully make it easier to generalize to other types of pattern.

Could you QuickCheck this to make sure it returns the same results?

**Comment by nicodelpiano** [comment]
:+1: ! Yes, I'd like to rewrite that now

**Comment by paf31** [comment]
I'd also like to investigate if we can break up the instances further into instances for e.g. `(,)`, `Either`, etc.

**Comment by nicodelpiano** [comment]
Sounds great! I'll do the same!

**Comment by nicodelpiano** [comment]
This is the instance I defined for quickCheck:

``` haskell
instance Arbitrary Binder where
  arbitrary = do
    _n <- choose (1,3) :: Gen Int
    case _n of
      1 -> return NullBinder
      2 -> return Zero
      _ -> do b <- arbitrary
              return (Succ b)

compare_missed bl br = uncover bl br == missed bl br
```

```
*** Failed! (after 26 tests):                             
Exception:
  Types.hs:(27,5)-(28,40): Non-exhaustive patterns in function go
NullBinder
Succ NullBinder
```

So, I fixed your definition adding the missing case:

``` haskell
instance Match Binder where
  missed _ NullBinder = []

  missed NullBinder b = go b
    where
    go Zero = [Succ NullBinder]
    go (Succ n) = Zero : map Succ (go n)
    go _ = []

  missed Zero Zero = []
  missed (Succ n) (Succ m) = map Succ (missed n m)

  missed b _ = [b]
```

And now it passes:

```
*Tests> quickCheck compare_missed
+++ OK, passed 100 tests.
```

Also, it passes with more complex examples:

``` haskell
instance Arbitrary Binder where
  arbitrary = do
    _n <- choose (1,30) :: Gen Int
    case _n of
      1 -> return NullBinder
      2 -> return Zero
      _ -> do b <- arbitrary
              return (Succ b)
```

**Comment by paf31** [comment]
Looks good!

**Comment by paf31** [comment]
I think you can use `oneOf` instead of `choose` by the way.

**Comment by paf31** [comment]
Also, prefer `fmap` to `do ... return` in the last case.

**Comment by nicodelpiano** [comment]
:+1:
