### ISSUE TITLE
Create a Cabal project

### ISSUE THREAD

**Issue by paf31** [nicodelpiano/stlcnat-exhaustivity-checker#3]
Eventually, we'll want to put this on Hackage, so let's start by packaging it up as a Cabal project. Later we can add it as a dependency in `purescript`.
- [x] A library with the `Match` class and its instances and functions
- [x] A separate test suite combining QuickCheck and unit tests (maybe with `test-framework`?)
- [x] Haddocks for documentation

**Comment by nicodelpiano** [comment]
What do you think about using `hspec` instead of `test-framework`?
I made some changes, if you wanna check them out.

**Comment by paf31** [comment]
Well `test-framework` just assembles different types of tests into groups, so you can use it with `hspec`, but let's stick with HSpec for now. Looks good!
